name: Deploy Static App
run-name: Deploy commit "${{ github.event.head_commit.message }}" pushed by @${{ github.actor }} to S3
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPOSITORY_NAME: react-vite-s3-cloudfront

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: npm install
      - name: Build static site
        run: npm run build
      - name: Configure
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: "${{ vars.AWS_REGION }}"
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ vars.AWS_S3_BUCKET_NAME }} --delete --region ${{ vars.AWS_REGION }}
